@echo off
cd backend
echo Setting up Python environment...
if not exist .venv (
    echo Creating virtual environment...
    python -m venv .venv
)
call .venv\Scripts\activate.bat
echo Installing dependencies...
pip install -r requirements.txt
echo Starting Uvicorn Server...
python -m uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
pause
